### ISSUE TITLE
Tracking: Seamless start and end

### ISSUE THREAD

**Issue by YtvwlD** [chaosdorf/freitagsfoo-infobeamer#1]
- [x] support having a background node
- [x] support configuring which node to use as background
- [x] support fading in from background
- [x] support fading out to background
- [x] support receiving commands
